<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $skincare = [
            [
                'name' => 'Organic Face Wash',
                'description' => 'A gentle face wash made from organic ingredients.',
                'long_description' => 'This Organic Face Wash is made from the finest organic ingredients, providing a gentle yet effective cleanse. It removes dirt, oil, and impurities without stripping your skin of its natural moisture. Perfect for all skin types, this face wash will leave your skin feeling fresh, clean, and rejuvenated. Use daily to maintain a clear and radiant complexion.',
                'price' => 15.99,
                'stock' => 100,
                'image_url' => 'images/product_1.jpg',
                'color' => 'White',
                'rating' => 4.5,
                'discount' => 10.00,
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Moisturizing Lotion',
                'description' => 'A lotion that keeps your skin hydrated all day.',
                'long_description' => 'Our Moisturizing Lotion is designed to provide long-lasting hydration, keeping your skin soft and smooth throughout the day. Enriched with natural emollients and vitamins, this lotion penetrates deep into the skin to nourish and moisturize from within. Ideal for daily use, it helps to maintain your skin’s natural moisture balance, making it perfect for all skin types.',
                'price' => 12.50,
                'stock' => 150,
                'image_url' => 'images/product_2.jpg',
                'color' => 'Pink',
                'rating' => 4.6,
                'discount' => 7.50,
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Vitamin C Serum',
                'description' => 'Brightens your skin with natural vitamin C.',
                'long_description' => 'Brighten and rejuvenate your skin with our Vitamin C Serum. Formulated with high-potency vitamin C, this serum helps to reduce the appearance of dark spots and hyperpigmentation, giving you a brighter and more even complexion. It also boosts collagen production, which helps to reduce fine lines and wrinkles. Suitable for all skin types, this serum will leave your skin looking radiant and youthful.',
                'price' => 25.00,
                'stock' => 80,
                'image_url' => 'images/product_3.jpg',
                'color' => 'Orange',
                'rating' => 4.8,
                'discount' => 5.00,
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Anti-Aging Cream',
                'description' => 'Reduces the appearance of fine lines and wrinkles.',
                'long_description' => 'Our Anti-Aging Cream is specially formulated to combat the signs of aging. It contains powerful anti-aging ingredients that help to reduce the appearance of fine lines and wrinkles, giving you smoother and younger-looking skin. The cream also hydrates and nourishes your skin, improving its overall texture and tone. With regular use, your skin will look firmer, plumper, and more radiant.',
                'price' => 30.00,
                'stock' => 60,
                'image_url' => 'images/product_4.jpg',
                'color' => 'White',
                'rating' => 4.9,
                'discount' => 15.00,
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rose Water Toner',
                'description' => 'Hydrates and refreshes your skin.',
                'long_description' => 'Refresh and hydrate your skin with our Rose Water Toner. This toner is made from pure rose water, which helps to balance your skin’s pH and tighten pores. It also provides a burst of hydration, leaving your skin feeling soft and refreshed. Ideal for all skin types, this toner can be used daily to maintain a healthy and glowing complexion.',
                'price' => 7.99,
                'stock' => 150,
                'image_url' => 'images/product_5.jpg',
                'color' => 'Pink',
                'rating' => 4.8,
                'discount' => 1.50,
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cleansing Balm',
                'description' => 'Removes makeup and impurities.',
                'long_description' => 'Our Cleansing Balm is a luxurious formula that melts away makeup and impurities, leaving your skin clean and hydrated. It contains nourishing oils and emollients that dissolve dirt and makeup while maintaining your skin’s natural moisture balance. Perfect for all skin types, this balm ensures a thorough cleanse without any greasy residue.',
                'price' => 20.00,
                'stock' => 50,
                'image_url' => 'images/product_6.jpg',
                'color' => 'Yellow',
                'rating' => 4.9,
                'discount' => 2.00,
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Face Toner',
                'description' => 'Balances and refreshes the skin.',
                'long_description' => 'Our Face Toner helps to balance and refresh your skin after cleansing. It removes any remaining impurities and prepares your skin for the next steps in your skincare routine. Enriched with natural extracts, this toner soothes and revitalizes your skin, leaving it feeling fresh and hydrated. Suitable for all skin types, it can be used daily for best results.',
                'price' => 11.00,
                'stock' => 140,
                'image_url' => 'images/product_7.jpg',
                'color' => 'Blue',
                'rating' => 4.7,
                'discount' => 1.50,
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        $haircare = [
            [
                'name' => 'Shampoo',
                'description' => 'A nourishing shampoo that cleanses and revitalizes your hair.',
                'long_description' => 'Our Shampoo is formulated to cleanse and nourish your hair, leaving it soft, shiny, and manageable. It contains natural ingredients that gently remove dirt and oil without stripping your hair of its natural moisture. Suitable for all hair types, this shampoo helps to maintain a healthy scalp and beautiful hair.',
                'price' => 12.99,
                'stock' => 120,
                'image_url' => 'images/product_8.jpg',
                'color' => 'Clear',
                'rating' => 4.5,
                'discount' => 2.00,
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Conditioner',
                'description' => 'A moisturizing conditioner that leaves hair soft and manageable.',
                'long_description' => 'Our Conditioner is designed to moisturize and detangle your hair, making it soft and manageable. It contains nourishing ingredients that hydrate and repair dry and damaged hair, leaving it looking healthy and shiny. Suitable for all hair types, this conditioner can be used daily to maintain beautiful and healthy hair.',
                'price' => 14.50,
                'stock' => 100,
                'image_url' => 'images/product_9.jpg',
                'color' => 'White',
                'rating' => 4.6,
                'discount' => 3.00,
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hair Mask',
                'description' => 'A deep conditioning treatment for damaged hair.',
                'long_description' => 'Our Hair Mask is a deep conditioning treatment that repairs and nourishes damaged hair. It contains natural oils and proteins that penetrate deep into the hair shaft, restoring moisture and strength. Use it once a week to keep your hair healthy, shiny, and manageable.',
                'price' => 20.00,
                'stock' => 70,
                'image_url' => 'images/product_10.jpg',
                'color' => 'Pink',
                'rating' => 4.7,
                'discount' => 5.00,
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hair Oil',
                'description' => 'Nourishes and strengthens hair with natural oils.',
                'long_description' => 'Our Hair Oil is a nourishing blend of natural oils that strengthen and condition your hair. It helps to reduce frizz, add shine, and improve the overall health of your hair. Apply a few drops to your hair and scalp to enjoy soft, shiny, and manageable hair. Suitable for all hair types, it can be used daily for best results.',
                'price' => 18.00,
                'stock' => 80,
                'image_url' => 'images/product_11.jpg',
                'color' => 'Gold',
                'rating' => 4.8,
                'discount' => 4.00,
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Leave-In Conditioner',
                'description' => 'A lightweight conditioner that can be left in for extra moisture.',
                'long_description' => 'Our Leave-In Conditioner is a lightweight formula that provides extra moisture and detangles your hair. It contains nourishing ingredients that hydrate and protect your hair throughout the day. Perfect for all hair types, this conditioner can be used daily to keep your hair soft, smooth, and manageable.',
                'price' => 13.00,
                'stock' => 150,
                'image_url' => 'images/product_12.jpg',
                'color' => 'White',
                'rating' => 4.5,
                'discount' => 2.50,
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Scalp Treatment',
                'description' => 'A treatment that soothes and revitalizes the scalp.',
                'long_description' => 'Our Scalp Treatment is a soothing formula that revitalizes your scalp and promotes healthy hair growth. It contains natural ingredients that nourish and soothe your scalp, reducing dryness and irritation. Use it regularly to maintain a healthy scalp and beautiful hair.',
                'price' => 16.00,
                'stock' => 90,
                'image_url' => 'images/product_13.jpg',
                'color' => 'Green',
                'rating' => 4.6,
                'discount' => 3.00,
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Volumizing Spray',
                'description' => 'Adds volume and body to fine hair.',
                'long_description' => 'Our Volumizing Spray is designed to add volume and body to fine and limp hair. It contains lightweight ingredients that lift your hair from the roots, giving it a fuller and thicker appearance. Suitable for all hair types, this spray can be used daily to achieve voluminous and beautiful hair.',
                'price' => 11.50,
                'stock' => 110,
                'image_url' => 'images/product_14.jpg',
                'color' => 'Clear',
                'rating' => 4.4,
                'discount' => 2.00,
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        $makeup = [
            [
                'name' => 'Foundation',
                'description' => 'A smooth foundation that provides full coverage.',
                'long_description' => 'Our Foundation offers full coverage with a smooth and lightweight texture. It blends seamlessly into your skin, creating a flawless and natural-looking finish. Available in various shades, this foundation is suitable for all skin types and can be used daily for a perfect complexion.',
                'price' => 25.00,
                'stock' => 150,
                'image_url' => 'images/product_15.jpg',
                'color' => 'Beige',
                'rating' => 4.6,
                'discount' => 5.00,
                'category_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mascara',
                'description' => 'A volumizing mascara for fuller lashes.',
                'long_description' => 'Our Mascara is designed to add volume and length to your lashes, creating a fuller and more dramatic look. The special formula ensures that your lashes stay curled and defined throughout the day. Perfect for daily use, this mascara enhances your eyes and adds a touch of glamour to your look.',
                'price' => 18.00,
                'stock' => 120,
                'image_url' => 'images/product_16.jpg',
                'color' => 'Black',
                'rating' => 4.7,
                'discount' => 3.00,
                'category_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lipstick',
                'description' => 'A rich, creamy lipstick available in various shades.',
                'long_description' => 'Our Lipstick is a rich and creamy formula that provides intense color and a smooth finish. Available in a variety of shades, it hydrates and nourishes your lips while giving them a bold and beautiful look. Perfect for any occasion, this lipstick will keep your lips looking vibrant and attractive.',
                'price' => 15.00,
                'stock' => 200,
                'image_url' => 'images/product_17.jpg',
                'color' => 'Red',
                'rating' => 4.8,
                'discount' => 2.00,
                'category_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Blush',
                'description' => 'A natural-looking blush to add a healthy glow.',
                'long_description' => 'Our Blush is a natural-looking formula that adds a healthy and radiant glow to your cheeks. It blends seamlessly into your skin, giving you a soft and rosy complexion. Available in various shades, this blush is perfect for adding a touch of color to your everyday look.',
                'price' => 22.00,
                'stock' => 140,
                'image_url' => 'images/product_18.jpg',
                'color' => 'Pink',
                'rating' => 4.5,
                'discount' => 3.00,
                'category_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Eyeshadow Palette',
                'description' => 'A palette with a variety of shades for versatile eye looks.',
                'long_description' => 'Our Eyeshadow Palette features a variety of shades that allow you to create versatile and stunning eye looks. Each shade is highly pigmented and easy to blend, providing a smooth and long-lasting finish. Perfect for both everyday wear and special occasions, this palette is a must-have in your makeup collection.',
                'price' => 30.00,
                'stock' => 100,
                'image_url' => 'images/product_19.jpg',
                'color' => 'Mixed',
                'rating' => 4.6,
                'discount' => 5.00,
                'category_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Eyeliner',
                'description' => 'A precise eyeliner for defining the eyes.',
                'long_description' => 'Our Eyeliner is a precise and easy-to-use formula that helps you define your eyes with accuracy. It glides smoothly across your eyelids, creating bold and sharp lines that stay put throughout the day. Perfect for both beginners and experts, this eyeliner enhances your eyes and adds a touch of drama to your look.',
                'price' => 12.00,
                'stock' => 180,
                'image_url' => 'images/product_20.jpg',
                'color' => 'Black',
                'rating' => 4.4,
                'discount' => 1.50,
                'category_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Setting Spray',
                'description' => 'A spray to set makeup and extend wear.',
                'long_description' => 'Our Setting Spray is a lightweight formula that helps to set your makeup and extend its wear throughout the day. It creates a protective barrier over your makeup, preventing it from smudging or fading. Suitable for all skin types, this spray ensures that your makeup looks fresh and flawless all day long.',
                'price' => 20.00,
                'stock' => 130,
                'image_url' => 'images/product_21.jpg',
                'color' => 'Clear',
                'rating' => 4.7,
                'discount' => 2.00,
                'category_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        $health_supplements = [
            [
                'name' => 'Multivitamins',
                'description' => 'A daily multivitamin supplement to support overall health.',
                'long_description' => 'Our Multivitamins provide a comprehensive blend of essential vitamins and minerals to support your overall health and wellbeing. Formulated to meet the nutritional needs of adults, these multivitamins help to boost your immune system, improve energy levels, and support healthy skin, hair, and nails. Take them daily to ensure you get the nutrients you need for optimal health.',
                'price' => 29.99,
                'stock' => 200,
                'image_url' => 'images/product_22.jpg',
                'color' => 'Yellow',
                'rating' => 4.7,
                'discount' => 5.00,
                'category_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Omega-3 Fish Oil',
                'description' => 'Rich in omega-3 fatty acids to support heart health.',
                'long_description' => 'Our Omega-3 Fish Oil is rich in essential fatty acids that support heart health, brain function, and overall wellbeing. It is sourced from high-quality fish and purified to remove any impurities, ensuring you get the best possible supplement. Take it daily to maintain a healthy heart and support your body’s vital functions.',
                'price' => 22.50,
                'stock' => 150,
                'image_url' => 'images/product_23.jpg',
                'color' => 'Clear',
                'rating' => 4.8,
                'discount' => 4.00,
                'category_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Probiotics',
                'description' => 'Supports digestive health with beneficial bacteria.',
                'long_description' => 'Our Probiotics contain a blend of beneficial bacteria that support your digestive health and improve your gut flora. These probiotics help to maintain a healthy balance of good bacteria in your gut, which is essential for digestion, nutrient absorption, and overall health. Take them daily to support a healthy digestive system.',
                'price' => 19.99,
                'stock' => 180,
                'image_url' => 'images/product_24.jpg',
                'color' => 'White',
                'rating' => 4.6,
                'discount' => 3.00,
                'category_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Vitamin D3',
                'description' => 'Helps maintain healthy bones and immune function.',
                'long_description' => 'Our Vitamin D3 supplements help to maintain healthy bones and support your immune function. Vitamin D3 is essential for calcium absorption, which is important for bone health and strength. It also helps to boost your immune system, keeping you healthy and protected. Take it daily to ensure you get the vitamin D3 your body needs.',
                'price' => 15.00,
                'stock' => 200,
                'image_url' => 'images/product_25.jpg',
                'color' => 'Yellow',
                'rating' => 4.5,
                'discount' => 2.00,
                'category_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Magnesium Complex',
                'description' => 'Supports muscle and nerve function with magnesium.',
                'long_description' => 'Our Magnesium Complex supplements provide a blend of magnesium that supports muscle and nerve function. Magnesium is essential for energy production, muscle contraction, and nerve transmission. It also helps to maintain healthy bones and supports your overall health. Take it daily to ensure you get the magnesium your body needs.',
                'price' => 18.00,
                'stock' => 160,
                'image_url' => 'images/product_26.jpg',
                'color' => 'White',
                'rating' => 4.7,
                'discount' => 2.50,
                'category_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Turmeric Curcumin',
                'description' => 'Natural anti-inflammatory supplement with turmeric.',
                'long_description' => 'Our Turmeric Curcumin supplements provide natural anti-inflammatory support with turmeric. Curcumin, the active ingredient in turmeric, helps to reduce inflammation and support joint health. It also has powerful antioxidant properties that protect your cells from damage. Take it daily to support your overall health and wellbeing.',
                'price' => 27.00,
                'stock' => 140,
                'image_url' => 'images/product_27.jpg',
                'color' => 'Orange',
                'rating' => 4.8,
                'discount' => 3.00,
                'category_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Protein Powder',
                'description' => 'High-quality protein powder for muscle recovery.',
                'long_description' => 'Our Protein Powder provides high-quality protein that supports muscle recovery and growth. It contains a blend of essential amino acids that help to repair and build muscle tissue. Perfect for athletes and fitness enthusiasts, this protein powder can be used as a post-workout supplement to support your muscle recovery and performance.',
                'price' => 35.00,
                'stock' => 110,
                'image_url' => 'images/product_28.jpg',
                'color' => 'Chocolate',
                'rating' => 4.6,
                'discount' => 5.00,
                'category_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Iron Supplements',
                'description' => 'Helps maintain healthy iron levels in the blood.',
                'long_description' => 'Our Iron Supplements help to maintain healthy iron levels in your blood, which is essential for oxygen transport and energy production. Iron is a vital nutrient that supports your overall health and wellbeing. Take it daily to ensure you get the iron your body needs.',
                'price' => 21.00,
                'stock' => 130,
                'image_url' => 'images/product_29.jpg',
                'color' => 'Red',
                'rating' => 4.4,
                'discount' => 3.00,
                'category_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        $body_care = [
            [
                'name' => 'Body Lotion',
                'description' => 'Hydrating body lotion with a rich, creamy texture.',
                'long_description' => 'Our Body Lotion is a rich and creamy formula that provides deep hydration for your skin. It contains nourishing ingredients that moisturize and soften your skin, leaving it feeling smooth and supple. Suitable for all skin types, this lotion can be used daily to maintain healthy and hydrated skin.',
                'price' => 24.00,
                'stock' => 130,
                'image_url' => 'images/product_30.jpg',
                'color' => 'White',
                'rating' => 4.6,
                'discount' => 3.00,
                'category_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Body Scrub',
                'description' => 'Exfoliating scrub to remove dead skin cells and leave skin smooth.',
                'long_description' => 'Our Body Scrub is an exfoliating formula that removes dead skin cells and leaves your skin feeling smooth and refreshed. It contains natural exfoliants that gently buff away rough and dry skin, revealing a softer and more radiant complexion. Suitable for all skin types, this scrub can be used weekly to maintain smooth and healthy skin.',
                'price' => 22.00,
                'stock' => 140,
                'image_url' => 'images/product_31.jpg',
                'color' => 'Pink',
                'rating' => 4.7,
                'discount' => 2.50,
                'category_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Body Wash',
                'description' => 'Gentle body wash with nourishing ingredients.',
                'long_description' => 'Our Body Wash is a gentle formula that cleanses and nourishes your skin. It contains natural ingredients that hydrate and soften your skin, leaving it feeling clean and refreshed. Suitable for all skin types, this body wash can be used daily to maintain healthy and beautiful skin.',
                'price' => 18.00,
                'stock' => 150,
                'image_url' => 'images/product_32.jpg',
                'color' => 'Clear',
                'rating' => 4.5,
                'discount' => 3.00,
                'category_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hand Cream',
                'description' => 'Rich hand cream to keep your hands soft and hydrated.',
                'long_description' => 'Our Hand Cream is a rich and nourishing formula that keeps your hands soft and hydrated. It contains natural moisturizers that protect and soothe your skin, leaving your hands feeling smooth and supple. Suitable for all skin types, this cream can be used daily to maintain healthy and beautiful hands.',
                'price' => 15.00,
                'stock' => 160,
                'image_url' => 'images/product_33.jpg',
                'color' => 'White',
                'rating' => 4.6,
                'discount' => 2.00,
                'category_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Body Oil',
                'description' => 'Nourishing body oil for deep hydration and a glowing complexion.',
                'long_description' => 'Our Body Oil is a luxurious formula that provides deep hydration and leaves your skin with a healthy glow. It contains nourishing oils that penetrate deep into your skin, providing long-lasting moisture and softness. Suitable for all skin types, this oil can be used daily to maintain healthy and radiant skin.',
                'price' => 30.00,
                'stock' => 120,
                'image_url' => 'images/product_34.jpg',
                'color' => 'Golden',
                'rating' => 4.8,
                'discount' => 4.00,
                'category_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'After-Sun Lotion',
                'description' => 'Cooling lotion to soothe skin after sun exposure.',
                'long_description' => 'Our After-Sun Lotion is a cooling and soothing formula that helps to relieve sunburn and hydrate your skin after sun exposure. It contains natural ingredients that reduce redness and inflammation, leaving your skin feeling refreshed and comfortable. Suitable for all skin types, this lotion can be used daily to maintain healthy and hydrated skin.',
                'price' => 25.00,
                'stock' => 130,
                'image_url' => 'images/product_35.jpg',
                'color' => 'White',
                'rating' => 4.8,
                'discount' => 4.00,
                'category_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        $essential_oils = [
            [
                'name' => 'Lavender Oil',
                'description' => 'Soothing lavender essential oil for relaxation.',
                'long_description' => 'Our Lavender Oil is a soothing essential oil that promotes relaxation and calm. It is perfect for aromatherapy, helping to reduce stress and improve sleep quality. You can also use it in your skincare routine to soothe and heal your skin. Suitable for all skin types, this oil can be used daily to enhance your overall wellbeing.',
                'price' => 18.00,
                'stock' => 150,
                'image_url' => 'images/product_36.jpg',
                'color' => 'Purple',
                'rating' => 4.8,
                'discount' => 2.00,
                'category_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Peppermint Oil',
                'description' => 'Refreshing peppermint essential oil for mental clarity.',
                'long_description' => 'Our Peppermint Oil is a refreshing essential oil that promotes mental clarity and focus. It is perfect for aromatherapy, helping to invigorate and energize your mind. You can also use it in your skincare routine to soothe and cool your skin. Suitable for all skin types, this oil can be used daily to enhance your overall wellbeing.',
                'price' => 20.00,
                'stock' => 140,
                'image_url' => 'images/product_37.jpg',
                'color' => 'Green',
                'rating' => 4.7,
                'discount' => 3.00,
                'category_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Eucalyptus Oil',
                'description' => 'Cleansing eucalyptus essential oil for respiratory support.',
                'long_description' => 'Our Eucalyptus Oil is a cleansing essential oil that supports respiratory health and wellbeing. It is perfect for aromatherapy, helping to clear your airways and improve breathing. You can also use it in your skincare routine to purify and refresh your skin. Suitable for all skin types, this oil can be used daily to enhance your overall wellbeing.',
                'price' => 22.00,
                'stock' => 130,
                'image_url' => 'images/product_38.jpg',
                'color' => 'Clear',
                'rating' => 4.6,
                'discount' => 2.50,
                'category_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tea Tree Oil',
                'description' => 'Antiseptic tea tree oil for skin care.',
                'long_description' => 'Our Tea Tree Oil is a powerful antiseptic essential oil that promotes healthy skin and hair. It is perfect for aromatherapy, helping to purify and cleanse your skin and scalp. You can also use it in your skincare routine to treat acne and other skin conditions. Suitable for all skin types, this oil can be used daily to enhance your overall wellbeing.',
                'price' => 25.00,
                'stock' => 120,
                'image_url' => 'images/product_39.jpg',
                'color' => 'Yellow',
                'rating' => 4.8,
                'discount' => 3.00,
                'category_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Frankincense Oil',
                'description' => 'Rejuvenating frankincense essential oil for skincare.',
                'long_description' => 'Our Frankincense Oil is a rejuvenating essential oil that promotes healthy and youthful skin. It is perfect for aromatherapy, helping to reduce the appearance of wrinkles and fine lines. You can also use it in your skincare routine to nourish and hydrate your skin. Suitable for all skin types, this oil can be used daily to enhance your overall wellbeing.',
                'price' => 30.00,
                'stock' => 110,
                'image_url' => 'images/product_40.jpg',
                'color' => 'Golden',
                'rating' => 4.9,
                'discount' => 4.00,
                'category_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ylang Ylang Oil',
                'description' => 'Sensual ylang ylang essential oil for relaxation and mood enhancement.',
                'long_description' => 'Our Ylang Ylang Oil is a sensual essential oil that promotes relaxation and mood enhancement. It is perfect for aromatherapy, helping to reduce stress and anxiety. You can also use it in your skincare routine to balance and hydrate your skin. Suitable for all skin types, this oil can be used daily to enhance your overall wellbeing.',
                'price' => 28.00,
                'stock' => 120,
                'image_url' => 'images/product_41.jpg',
                'color' => 'Yellow',
                'rating' => 4.8,
                'discount' => 4.00,
                'category_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        $oral_care = [
            [
                'name' => 'Whitening Toothpaste',
                'description' => 'Toothpaste designed to remove stains and whiten teeth.',
                'long_description' => 'Our Whitening Toothpaste is a powerful formula that removes stains and whitens your teeth. It contains gentle abrasives and whitening agents that polish your teeth, leaving them looking bright and clean. Suitable for daily use, this toothpaste helps to maintain a healthy and beautiful smile.',
                'price' => 12.00,
                'stock' => 150,
                'image_url' => 'images/product_42.jpg',
                'color' => 'White',
                'rating' => 4.5,
                'discount' => 2.00,
                'category_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mouthwash',
                'description' => 'Antimicrobial mouthwash for fresh breath and oral hygiene.',
                'long_description' => 'Our Mouthwash is a refreshing formula that helps to maintain fresh breath and oral hygiene. It contains antimicrobial agents that kill bacteria and prevent plaque buildup, keeping your mouth clean and healthy. Suitable for daily use, this mouthwash helps to maintain a healthy and beautiful smile.',
                'price' => 15.00,
                'stock' => 130,
                'image_url' => 'images/product_43.jpg',
                'color' => 'Blue',
                'rating' => 4.6,
                'discount' => 2.50,
                'category_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Fluoride Toothpaste',
                'description' => 'Fluoride toothpaste to help prevent cavities.',
                'long_description' => 'Our Fluoride Toothpaste is a protective formula that helps to prevent cavities and tooth decay. It contains fluoride, which strengthens your tooth enamel and protects against acid erosion. Suitable for daily use, this toothpaste helps to maintain a healthy and beautiful smile.',
                'price' => 10.00,
                'stock' => 140,
                'image_url' => 'images/product_44.jpg',
                'color' => 'White',
                'rating' => 4.7,
                'discount' => 1.50,
                'category_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Electric Toothbrush',
                'description' => 'Electric toothbrush with multiple cleaning modes.',
                'long_description' => 'Our Electric Toothbrush is a high-performance toothbrush that offers multiple cleaning modes to suit your oral care needs. It features advanced technology that provides a thorough and gentle clean, removing plaque and promoting healthy gums. Suitable for daily use, this toothbrush helps to maintain a healthy and beautiful smile.',
                'price' => 60.00,
                'stock' => 120,
                'image_url' => 'images/product_45.jpg',
                'color' => 'Black',
                'rating' => 4.8,
                'discount' => 10.00,
                'category_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dental Floss',
                'description' => 'Mint-flavored dental floss for effective interdental cleaning.',
                'long_description' => 'Our Dental Floss is a mint-flavored formula that provides effective interdental cleaning. It removes plaque and food particles from between your teeth, promoting healthy gums and preventing cavities. Suitable for daily use, this floss helps to maintain a healthy and beautiful smile.',
                'price' => 8.00,
                'stock' => 180,
                'image_url' => 'images/product_46.jpg',
                'color' => 'White',
                'rating' => 4.4,
                'discount' => 1.00,
                'category_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tooth Whitening Kit',
                'description' => 'Complete kit for at-home tooth whitening.',
                'long_description' => 'Our Tooth Whitening Kit is a complete system that allows you to whiten your teeth at home. It contains professional-grade whitening agents that remove stains and brighten your teeth, giving you a beautiful and radiant smile. Suitable for daily use, this kit helps to maintain a healthy and beautiful smile.',
                'price' => 45.00,
                'stock' => 100,
                'image_url' => 'images/product_47.jpg',
                'color' => 'White',
                'rating' => 4.7,
                'discount' => 5.00,
                'category_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        $mens_grooming = [
            [
                'name' => 'Beard Oil',
                'description' => 'Nourishing beard oil to soften and condition facial hair.',
                'long_description' => 'Our Beard Oil is a nourishing blend of natural oils that softens and conditions your beard. It helps to reduce itchiness and flakiness, keeping your beard healthy and manageable. Suitable for all beard types, this oil can be used daily to maintain a soft and well-groomed beard.',
                'price' => 25.00,
                'stock' => 130,
                'image_url' => 'images/product_48.jpg',
                'color' => 'Amber',
                'rating' => 4.7,
                'discount' => 3.00,
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Shaving Cream',
                'description' => 'Rich shaving cream for a smooth, close shave.',
                'long_description' => 'Our Shaving Cream is a rich and creamy formula that provides a smooth and close shave. It contains moisturizing ingredients that protect your skin from irritation and razor burn, leaving it soft and smooth. Suitable for all skin types, this cream can be used daily to maintain a clean and comfortable shave.',
                'price' => 20.00,
                'stock' => 140,
                'image_url' => 'images/product_49.jpg',
                'color' => 'White',
                'rating' => 4.6,
                'discount' => 2.50,
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Aftershave Balm',
                'description' => 'Soothing aftershave balm to reduce irritation and hydrate skin.',
                'long_description' => 'Our Aftershave Balm is a soothing formula that reduces irritation and hydrates your skin after shaving. It contains natural ingredients that calm and nourish your skin, leaving it feeling soft and refreshed. Suitable for all skin types, this balm can be used daily to maintain healthy and comfortable skin.',
                'price' => 22.00,
                'stock' => 120,
                'image_url' => 'images/product_50.jpg',
                'color' => 'Clear',
                'rating' => 4.8,
                'discount' => 2.00,
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hair Styling Gel',
                'description' => 'Strong hold hair gel for creating and maintaining hairstyles.',
                'long_description' => 'Our Hair Styling Gel is a strong hold formula that helps you create and maintain your desired hairstyle. It provides long-lasting hold and control without flaking or buildup, leaving your hair looking natural and well-groomed. Suitable for all hair types, this gel can be used daily to achieve a polished look.',
                'price' => 18.00,
                'stock' => 150,
                'image_url' => 'images/product_51.jpg',
                'color' => 'Clear',
                'rating' => 4.5,
                'discount' => 1.50,
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Face Cleanser',
                'description' => 'Gentle face cleanser for daily use and deep cleaning.',
                'long_description' => 'Our Face Cleanser is a gentle formula that provides deep cleaning and removes dirt, oil, and impurities from your skin. It contains natural ingredients that hydrate and soothe your skin, leaving it feeling clean and refreshed. Suitable for all skin types, this cleanser can be used daily to maintain healthy and beautiful skin.',
                'price' => 15.00,
                'stock' => 160,
                'image_url' => 'images/product_52.jpg',
                'color' => 'Blue',
                'rating' => 4.6,
                'discount' => 2.00,
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Moisturizing Cream',
                'description' => 'Hydrating cream for keeping skin smooth and moisturized.',
                'long_description' => 'Our Moisturizing Cream is a hydrating formula that keeps your skin smooth and moisturized. It contains nourishing ingredients that protect and soothe your skin, leaving it feeling soft and supple. Suitable for all skin types, this cream can be used daily to maintain healthy and hydrated skin.',
                'price' => 27.00,
                'stock' => 110,
                'image_url' => 'images/product_53.jpg',
                'color' => 'White',
                'rating' => 4.7,
                'discount' => 3.00,
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Deodorant',
                'description' => 'Long-lasting deodorant for all-day freshness.',
                'long_description' => 'Our Deodorant is a long-lasting formula that provides all-day freshness and odor protection. It contains natural ingredients that neutralize odor and keep you feeling confident and fresh. Suitable for all skin types, this deodorant can be used daily to maintain healthy and comfortable underarms.',
                'price' => 10.00,
                'stock' => 180,
                'image_url' => 'images/product_54.jpg',
                'color' => 'White',
                'rating' => 4.4,
                'discount' => 1.00,
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Beard Shampoo',
                'description' => 'Specially formulated shampoo for cleansing and conditioning beards.',
                'long_description' => 'Our Beard Shampoo is a specially formulated shampoo that cleanses and conditions your beard. It contains natural ingredients that remove dirt and impurities, leaving your beard feeling soft and manageable. Suitable for all beard types, this shampoo can be used daily to maintain a clean and healthy beard.',
                'price' => 19.00,
                'stock' => 140,
                'image_url' => 'images/product_55.jpg',
                'color' => 'Clear',
                'rating' => 4.6,
                'discount' => 2.00,
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hair Conditioner',
                'description' => 'Conditioner to keep hair soft and manageable.',
                'long_description' => 'Our Hair Conditioner is a nourishing formula that keeps your hair soft and manageable. It contains natural ingredients that hydrate and detangle your hair, leaving it feeling smooth and shiny. Suitable for all hair types, this conditioner can be used daily to maintain healthy and beautiful hair.',
                'price' => 16.00,
                'stock' => 150,
                'image_url' => 'images/product_56.jpg',
                'color' => 'Clear',
                'rating' => 4.5,
                'discount' => 1.50,
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hair Pomade',
                'description' => 'Classic pomade for styling and shaping hair.',
                'long_description' => 'Our Hair Pomade is a classic styling product that helps you create and shape your desired hairstyle. It provides a strong hold and a smooth finish, giving your hair a polished and refined look. Suitable for all hair types, this pomade can be used daily to achieve a stylish and well-groomed appearance.',
                'price' => 21.00,
                'stock' => 130,
                'image_url' => 'images/product_57.jpg',
                'color' => 'Brown',
                'rating' => 4.7,
                'discount' => 2.00,
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('products')->insert($skincare);
        DB::table('products')->insert($haircare);
        DB::table('products')->insert($makeup);
        DB::table('products')->insert($health_supplements);
        DB::table('products')->insert($body_care);
        DB::table('products')->insert($essential_oils);
        DB::table('products')->insert($oral_care);
        DB::table('products')->insert($mens_grooming);
    }
}
