version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: well
    volumes:
      - ./storage:/var/www/storage
    depends_on:
      - mysql
    networks:
      - app-net
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./public:/var/www/public
    depends_on:
      - app
    networks:
      - app-net

  mysql:
    image: 'mysql/mysql-server:8.0'
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  mysql-data:
