    [supervisord]
    nodaemon=true ; Run Supervisor in the foreground
    user=root     ; Supervisor itself runs as root to manage processes

    [program:php-fpm]
    command=/usr/local/sbin/php-fpm -F --allow-to-run-as-root
    autostart=true
    autorestart=true
    priority=5
    stdout_logfile=/dev/stdout
    stdout_logfile_maxbytes=0
    stderr_logfile=/dev/stderr
    stderr_logfile_maxbytes=0
    user=www-data ; Run php-fpm as www-data

    [program:nginx]
    command=/usr/sbin/nginx -g 'daemon off;'
    autostart=true
    autorestart=true
    priority=10
    stdout_logfile=/dev/stdout
    stdout_logfile_maxbytes=0
    stderr_logfile=/dev/stderr
    stderr_logfile_maxbytes=0
    user=root ; Nginx master process runs as root, workers as www-data (configured in nginx.conf)

    ; You can add your queue worker here if needed
    ; [program:laravel-worker]
    ; process_name=%(program_name)s_%(process_num)02d
    ; command=php /var/www/html/artisan queue:work --sleep=3 --tries=3 --max-time=3600
    ; autostart=true
    ; autorestart=true
    ; stopasgroup=true
    ; killasgroup=true
    ; user=www-data
    ; numprocs=1 ; Number of worker processes
    ; redirect_stderr=true
    ; stdout_logfile=/var/www/html/storage/logs/worker.log
    ; stopwaitsecs=3600
